const LM = [
  {
    id: "l1",
    name: "Klonidin",
    styrka: "15 µg/ml",
    recept: "1 ml catapressan 150 µg/ml + 9 ml NaCl",
    dosimG: "",
    dosIµG: 1,
    obs: "barn > 1 år",
  },
  {
    id: "l2",
    name: "Ondansetron",
    styrka: "2 mg/ml",
    recept: "",
    dosimG: 0.1,
    dosIµG: "",
    obs: "maximalt 4 mg",
  },
  {
    id: "l3",
    name: "Betapred",
    styrka: "4 mg/ml",
    recept: "",
    dosimG: 0.2,
    dosIµG: "",
    obs: "maximalt 4 mg",
  },
  {
    id: "l4",
    name: "Phenergan",
    styrka: "25 mg/ml",
    recept: "",
    dosimG: 0.5,
    dosIµG: "",
    obs: "maximalt 12,5 mg",
  },
  {
    id: "l5",
    name: "Ondansetron",
    styrka: "2 mg/ml",
    recept: "",
    dosiMg: 0.1,
    dosIµG: "",
    obs: "maximalt 4 mg",
  },
  {
    id: "l6",
    name: "Atropin inj.",
    styrka: "0.5 mg/ml",
    recept: "",
    dosiMg: "",
    dosIµG: 10,
    obs: "maximalt 0.5 mg",
  },
];

export default LM;
